# This is a basic workflow to help you get started with Actions
name: Self Hosted Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - '.github/workflows/self-hosted.yml'
      - 'GNUmakefile'
      - 'Dockerfile.alpine'

    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu18-docker-self:
    runs-on: self-hosted

    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Make
        run: |
          #[[ -d ~/Bitcoin.org ]] && echo "~/Bitcoin.org exists!!!" || git clone https://github.com/bitcoin-dot-org/Bitcoin.org.git ~/Bitcoin.org
          cd ~/org-builder
          SITE=~/Bitcoin.org make image

  ubuntu18-make-image-self:
    runs-on: self-hosted
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Make
        run: |
          cd ~/org-builder
          make image port=1234

