# This is a basic workflow to help you get started with Actions
name: Self Hosted Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #paths:
    #  - '.github/workflows/self-hosted.yml'
    #  - 'GNUmakefile'
    #  - 'Dockerfile.alpine'

    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  self-hosted1:
    runs-on: self-hosted
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: self-hosted1
        run: |
          echo ${{ runner.os }}
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt -y install make docker.io
          [[ -d ~/Bitcoin.org ]] && echo "~/Bitcoin.org exists!!!" || \
          git clone https://github.com/bitcoin-dot-org/Bitcoin.org.git ~/Bitcoin.org
          sudo SITE=~/Bitcoin.org make image
          fi
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install  make docker
          [[ -d ~/Bitcoin.org ]] && echo "~/Bitcoin.org exists!!!" || \
          git clone https://github.com/bitcoin-dot-org/Bitcoin.org.git ~/Bitcoin.org
              SITE=~/Bitcoin.org make image
          fi

  self-hosted2:
    runs-on: self-hosted
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: self-hosted2
        run: |
          echo ${{ runner.os }}
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt -y install make docker.io
            sudo make image port=1234
          fi
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install make docker
            make image port=1234
          fi

